#!/usr/bin/env bash
# Local production build — mirrors the transform in
# .github/workflows/deploy-pages.yml (the "bundle jsx" step).
#
# Produces ./dist: Babel stripped, all JSX pre-compiled and minified into a
# single app.min.js, index.html rewritten to load it. This is what gh-pages
# actually serves, so you can preview/measure the real thing locally.
# The source tree is left untouched (CI does its rewrite in place on a
# throwaway runner; we don't want that on your working copy).
#
#   ./build.sh              # build into ./dist
#   python -m http.server -d dist 8000   # then preview at localhost:8000
set -euo pipefail
cd "$(dirname "$0")"

OUT=dist
# Load order must match the <script> tags in index.html.
COMPONENTS="Chrome Chart Nav Hero About Portfolio Polymarket Combined Politics Writing App"

rm -rf "$OUT"
mkdir -p "$OUT"

# --- static assets -----------------------------------------------------------
cp index.html colors_and_type.css "$OUT"/
cp -r assets data "$OUT"/
[ -f feed.xml ] && cp feed.xml "$OUT"/   # generated by CI; copied if present

# --- bundle + minify JSX into one file --------------------------------------
: > "$OUT/app.min.js"
for f in $COMPONENTS; do
  npx -y esbuild@0.25.0 "$f.jsx" --format=iife --minify >> "$OUT/app.min.js"
done

# --- rewrite index.html: drop Babel, load the compiled bundle ---------------
sed -i '/@babel\/standalone/d' "$OUT/index.html"
sed -i 's|<script type="text/babel" src="Chrome.jsx"></script>|<script src="app.min.js"></script>|' "$OUT/index.html"
sed -i '/type="text\/babel"/d' "$OUT/index.html"
grep -q 'app.min.js' "$OUT/index.html"   # fail loudly if the rewrite missed

echo "built -> $OUT/  (preview: python -m http.server -d $OUT 8000)"
